### ISSUE TITLE
MAC OS X: Can't start Quark.jar

### ISSUE THREAD

**Issue by paoloalby** [XorTroll/Goldleaf#398]
# Can't start Quark.jar

## Bug description

if I double click on Quark.jar it crashes with the popup
"Can't run file JAR Java "Quart.jar"
Check the Console for error messages.

Then, I run "java -jar Quark.jar
And here the result

`WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.1
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/PaintConverter
	at com.jfoenix.controls.JFXTextArea$StyleableProperties.<clinit>(JFXTextArea.java:221)
	at com.jfoenix.controls.JFXTextArea.<init>(JFXTextArea.java:145)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:560)
	at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1019)
	at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
	at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at xorTroll.goldleaf.quark.ui.MainApplication.start(MainApplication.java:103)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.PaintConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 20 more
`

## Your setup

- **OS**: Mac OS X

- **Java**: Java 8 upsate 221

## Additional information

I can execute other jar files without any problem, usbloader for example.. 
So I don't think it's my java fault.

**Comment by lookye** [comment]
Same as #393 
Side note: Im running OSX + Java and Quark works as intended (Opens via double click).
Make sure you set up Java and the dependencies correctly (Same as for ns-usbloader)

<img width="510" alt="Screenshot" src="https://user-images.githubusercontent.com/45557556/65326939-ed18d500-dbb2-11e9-9d5e-6bd7d85e8143.png">

**Comment by sjogro** [comment]
<img width="532" alt="Screenshot 2019-09-20 at 15 12 13" src="https://user-images.githubusercontent.com/6476418/65329608-176d9100-dbb9-11e9-919e-ca89d34526ab.png">

Sadly, no, new Quark.jar gives the same error.
How do I setup Java and dependencies correctly for Quark.jar? ns-usbloader.jar opens fine.

My .jar files open with Jar Launcher.app (15.0.1)

**Comment by lookye** [comment]
Try deleting and installing the latest JRE again.

**Comment by sjogro** [comment]
Installed Version 8 Update 221
https://www.java.com/nl/download/mac_download.jsp

Now it works!

**Comment by cminois** [comment]
Hi,

I had the same issue on MacOS using OpenJDK version 11.
I solved it by updating the version of jfoenix library to 9.0.9 and rebuilding Quark.

**Comment by lookye** [comment]
#392 As a collecting point
