### ISSUE TITLE
Quark on macOS issues

### ISSUE THREAD

**Issue by sanhuoO** [XorTroll/Goldleaf#452]
# [Quark] Error:Exception in thread "main" java.lang.RuntimeException: Exception in Application start method

## Bug description

$ java -version
java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

$ java -jar Quark.jar
11月 14, 2019 12:16:48 上午 javafx.fxml.FXMLLoader$ValueElement processValue
警告: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 11
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/PaintConverter
	at com.jfoenix.controls.JFXTextArea$StyleableProperties.<clinit>(JFXTextArea.java:221)
	at com.jfoenix.controls.JFXTextArea.<init>(JFXTextArea.java:145)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
	at java.base/java.lang.Class.newInstance(Class.java:591)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1019)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at xorTroll.goldleaf.quark.ui.MainApplication.start(MainApplication.java:103)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.PaintConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 22 more

## Your setup

- **Quark **: [ 0.7.3 maybe 0.7.2 ]

- **macOS**: [ 10.15.1  ]

- **JDK**: [ 13.0.1+9 ]

## Bug reproduction

Launch Quark.jar 
java -jar Quark.jar

**Comment by evilarceus** [comment]
Same issue on Arch Linux. I tried Java 8, 10, 11, and 13, all of which give the same error.
I remember fixing this issue on Windows by installing the latest version of Java 8, but that doesn't seem to work on Arch Linux :/

**Comment by hicsuntdragons** [comment]
Had the same problems on Arch Linux / Manjaro, and solved them by building the `.jar` from source!
I used `java-13-openjdk`, just cloned the repo, mounted to Quark folder and ran the `build.sh` file. Make sure to have `Maven` installed. I believe a similar build process for macOS should work as well?

**Comment by lookye** [comment]
Please test the latest release. Make sure to open the .jar via cmd/terminal `java -jar "quark_file_here"`
