### ISSUE TITLE
Unknown Id: 15

### ISSUE THREAD

**Issue by yourenotyourwallet** [XorTroll/Goldleaf#486]
# Unknown Id: 15

## Bug description

When I try to explore the content of my mac remotely via USB in Goldleaf, while Quark.jar is running on my mac, I get a "Unknown Id: 15" message on the log in Quark, and I cannot do anything in Goldleaf on the Switch, it doesn't show the content of my disk, I have to quit (home button) and relaunch it.
By the way, I can't run the latest version of Quark (associated with Goldleaf 0.8), the older ones work (0.2.0 and older)

## Your setup

- **Console firmware**: 9.1.0

- **CFW with version**: Atmosphere

- **Goldleaf version**: 0.8

- **Goldtree version**: [ e.g. 0.5 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information
I run Mac os x 10.11.6 with java 8 / 241
ns-usbloader-1.0 works fine

**Comment by XorTroll** [comment]
Update Quark

**Comment by yourenotyourwallet** [comment]
I can't open the Quark version included in Goldleaf 0.8. When I launch Quark.jar, I get an error message: Impossible to run: Check console for errors (translated)
I tried to fix this issue by searching the net, but none of the solutions worked (uninstalling and reinstalling java...)

**Comment by yourenotyourwallet** [comment]
I get this message in the terminal when I try to run the latest version of Quark:

Exception in thread "main" java.lang.UnsupportedClassVersionError: xorTroll/goldleaf/quark/Main : Unsupported major.minor version 53.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
