### ISSUE TITLE
Can't run the latest version of quark

### ISSUE THREAD

**Issue by yourenotyourwallet** [XorTroll/Goldleaf#487]
# Can't run the latest version of quark

## Bug description

I can't open the Quark version included in Goldleaf 0.8. When I launch Quark.jar, I get an error message: Impossible to run: Check console for errors (translated)
I tried to fix this issue by searching the net, but none of the solutions worked (uninstalling and reinstalling java...)

I get this message in the terminal when I try to run the latest version of Quark:

Exception in thread "main" java.lang.UnsupportedClassVersionError: xorTroll/goldleaf/quark/Main : Unsupported major.minor version 53.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

## Your setup

- **Console firmware**: 9.1.0

- **CFW with version**: Atmosphere

- **Goldleaf version**: 0.8

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

The previous versions of Quark worked (0.2.0)

**Comment by XorTroll** [comment]
Which java version do you have?

**Comment by yourenotyourwallet** [comment]
I'm using java 8 / 241 on mac os

**Comment by XorTroll** [comment]
https://github.com/XorTroll/Goldleaf/blob/master/Quark.md
