### ISSUE TITLE
Quark fails to run because of exceptions thrown

### ISSUE THREAD

**Issue by benjamin32561** [XorTroll/Goldleaf#512]
# [ Bug report title ]

## Bug description

[ Please describe your bug as detailed as possible here. ]

## Your setup

- **Console firmware**: [ e.g. 5.1, 6.2, 7.0.1 ]

- **CFW with version**: [ e.g. ReiNX 2.1 or Atmosphere 0.85 ]

- **Goldleaf version**: [ e.g. 0.5 or the exact nightly build ]

- **Goldtree version**: [ e.g. 0.5 ]

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]

## Additional information

[ Please add some extra information or screenshots. ]

**Comment by benjamin32561** [comment]
hi im using the Quark and when i run it it fails with this exeptions:
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 11
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/converters/PaintConverter
        at com.jfoenix.controls.JFXTextArea$StyleableProperties.<clinit>(JFXTextArea.java:221)
        at com.jfoenix.controls.JFXTextArea.<init>(JFXTextArea.java:145)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
        at java.base/java.lang.Class.newInstance(Class.java:591)
        at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1019)
        at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
        at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
        at xorTroll.goldleaf.quark.ui.MainApplication.start(MainApplication.java:103)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.converters.PaintConverter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 25 more

**Comment by lookye** [comment]
What OS are you using?

**Comment by ttimasdf** [comment]
+1, Windows with OpenJDK is not enough to run Quark because of the lack of JavaFX.

**Comment by benjamin32561** [comment]
windows 10

**Comment by benjamin32561** [comment]
> What OS are you using?

windows 10

**Comment by benjamin32561** [comment]
> +1, Windows with OpenJDK is not enough to run Quark because of the lack of JavaFX.

so i need to download JavaFX?

**Comment by ttimasdf** [comment]
> 
> 
> > +1, Windows with OpenJDK is not enough to run Quark because of the lack of JavaFX.
> 
> so i need to download JavaFX?

I tried. Not work.

- AdoptOpenJDK 11 + JavaFX from [openjfx.io](//openjfx.io)
  - Still throw `java.lang.ClassNotFoundException`
- [Zulu OpenJDK](https://www.azul.com/downloads/zulu-community/?os=windows) 11 with JFX bundled(Maybe? I download the version of `JRE FX`, they don't have a doc about the differences)
  - Still throw `java.lang.ClassNotFoundException`, it should work but ... oh weird
- JDK8 installed through [chocolatey](https://chocolatey.org/)
  - The Quark runs, but Goldleaf freeze when browsing content from PC, maybe a Goldleaf issue?
- [nut](https://github.com/blawar/nut/releases) + Tinfoil
  - Works smoothly 🙈

**Comment by ScallyK** [comment]
https://www.oracle.com/java/technologies/javase-jdk13-downloads.html

This is the solution. Download the latest JDK.

**Comment by ttimasdf** [comment]
I think I've found the problem. The `Quark.jar` provided in the [latest release](https://github.com/XorTroll/Goldleaf/releases) just not work on Java 9 above, at least on Windows. It's an old version that only run under Java 8 with JavaFX.

I compile a newer version from source codes and it works with AdoptOpenJDK 11 without problem.
There should be some documentation here, so much misleading.,
