### ISSUE TITLE
Quark does not open using jdk 16.0.2 (Win)

### ISSUE THREAD

**Issue by Praeca** [XorTroll/Goldleaf#634]
# [ Bug report title ]
Quark does not open using jdk 16.0.2
## Bug description
Quark does not open regardless of double clicked on or opened via CMD

\directory>java -jar Quark.jar
Feb 11, 2022 12:38:41 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4427f35e'
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:831)
## Your setup

- **Quark version**: 
Quark 5.0
- **JDK Version:**
Eclipse Foundation JDK-16.0.2.7-hotspot
- **OS:**
Windows 10

## Bug reproduction

[ Describe as detailed as possible how to reproduce your bug, for others to be able to verify it. ]
Install Open JDK version and attempt to open file

## Additional information

C:\Users\Admin>java -version
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)

C:\Users\Admin>javac -version
javac 16.0.2

C:\Users\Admin>

**Comment by XorTroll** [comment]
[Quark.zip](https://github.com/XorTroll/Goldleaf/files/8045281/Quark.zip)

Can you try with this build?

**Comment by MatrixDev** [comment]
@XorTroll, I have the same issue on MacOS (arm). Provided zip file didn't help.

**Comment by MatrixDev** [comment]
Found the problem. My PC has different Java version installed:
```
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)
```

Azul JDK doesn't contain JavaFX, and I had to install it manually:
```
brew install --cask zulufx
```

Now everything works. Maybe it will help someone else.

**Comment by XorTroll** [comment]
Added a note on the README warning about this
